apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cogilent-net-tls
spec:
  secretName: cogilent-net-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: cogilent.net
  dnsNames:
    - cogilent.net
    - www.cogilent.net