apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: cogilent.net
  dnsNames:
    - cogilent.net
    - www.cogilent.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - cogilent.net
          - www.cogilent.net